# Getting Started

Your first few steps in this course are to:

1. Register and enroll via the [CWRU Student Information System (SIS)](https://sis.case.edu/).
    - Section 100 of PQHS 431, CRSP 431 and MPHP 431 are identical.
2. Review the [main course website](https://thomaselove.github.io/431-2023), and be sure to visit the [Course Calendar](https://thomaselove.github.io/431-2023/calendar.html), and skim through the Course Syllabus (this document.)
3. Obtain the texts required for the course. There is only one book you need to purchase, listed below. See @sec-requiredtexts for details on the other required texts.
4. Complete the [Welcome to 431 survey](https://bit.ly/431-2022-welcome-survey) - see below for details.
5. Get started installing the software you'll need for the course. See @sec-requiredsoftware for more details.

## What Do I Need To Purchase?

You need to buy David Spiegelhalter's **The Art of Statistics**. You can purchase any of the available versions (hard-cover, paperback or e-reader) online or in your local bookstore for about $20.

Everything else (including several other required texts) will be free, and is described in detail in @sec-requiredtexts of this Syllabus.

## Welcome to 431 Survey 

Please fill out the [Welcome to 431 Survey](https://bit.ly/431-2023-welcome-survey) at https://bit.ly/431-2023-welcome-survey to help us get to know you a little better.

- Note that you must **log into Google via your CWRU account** in order to access the survey.
- The survey should take 15-20 minutes to complete, and we encourage you to complete it as soon as you can.
  