# Teaching Assistants {#sec-teachingassistants}

Most of this year's stellar group of teaching assistants have been in your shoes - they've taken the course in the past, and they enjoyed it enough to come back for more. They are volunteering their precious time and energy to help make the course happen, and we couldn't be more delighted to welcome you to the course. All office hours and all teaching assistant work will be done remotely.

There is a lot to learn in this class. Don't suffer in silence - talk to us! As mentioned earlier, **you shouldn't spend more than 15 minutes struggling with anything in this class without asking for help.**

Visit the Getting Help Chapter (@sec-gettinghelp) of this Syllabus for more details.

The Fall 2023 Teaching Assistants for 431 are:

- Ali Elsharkawi, MS student in Clinical Research
- Chenyu Liu, PhD student in Epidemiology \& Biostatistics
- Alex Olejko, PhD student in Psychology
- Lindsay Petrenchik, MS graduate in Epidemiology \& Biostatistics
- Monika Strah, PhD student in Clinical Translational Science
- Ria Tilve, MPH graduate in Population Health Research, and current MD student

## TA office hours

TA office hours are held via Zoom, will begin in early September and end in early December. The weekly schedule will appear on our [Contact Us page](https://thomaselove.github.io/431-2023/contact.html) as well as our [Course Calendar](https://thomaselove.github.io/431-2023/calendar.html).

- Our Shared Google Drive (431 Fall 2023 Dr Love and Students) will eventually contain Zoom links for each of these sessions in a document called **TA office hours schedule and Zoom links**. 
  - No appointment is necessary. Please just drop in. 
  - Be sure to log into Google via CWRU to access the shared Drive.
- TA office hours are cancelled from 2023-11-19 through 2023-11-25 for Thanksgiving break.

Professor Love will also hold "office hours" before and after each class to the extent possible.

## Getting To Know The TAs

Details to come.
