# Grading

Over the past five years, all students taking the course have eventually earned either an "A", a "B" or an "Incomplete" in 431. I don't see a reason why this won't also be the case this year. The course cannot be taken "pass/fail."

## Grading Breakdown

Grading standards apply in the same way for all students, regardless of whether they are enrolled in PQHS 431, CRSP 431 or MPHP 431. Students in this class are not in competition with each other for grades. I have no set percentage of students who will receive any particular grade. We aim for substantial and timely feedback from the teaching assistants and myself on all elements of the course.

The course grade is based on four key areas of demonstrated accomplishment. 

Course grades are based primarily on performance on labs, projects and quizzes. Your grade on each of these three elements will be determined separately. Then we will combine these elements as follows:

Element | Weight 1 | Weight 2 | Weight 3 | Weight 4
:-------: | :--------: | :--------: | :--------: | :--------:
Labs | 35% | 30% | 25% | -
Projects | 45% | 40% | 35% | -
Quizzes | 25% | 20% | 15% | -
Participation | - | - | - | 10%

Among Labs, Projects and Quizzes, your element with the strongest score will receive Weight 1, your element with the second strongest score will receive Weight 2 and your element with the weakest score will receive weight 3. The Class Participation score (which includes the Minute Papers) is worth 10% for all students.

Professor Love will then determine your final course grade using the following scale:

- course averages of 88.0% to 100% will receive a A
- course averages of 85.0% to 87.9% will be reviewed more closely to determine whether the grade will be A or B
- course averages of 70.0% to 84.9% will receive a B

For students in the 85.0-87.9% range, students who have improved from the first half of the course to the second will be more likely to receive an A than those whose performance has declined. 

Students whose course average is near or below 70% usually have failed to complete some element of the course, and need to take an Incomplete to complete their work before I assign a final grade. We follow the University's Incomplete Policy, as describe below.

## Grading Class Participation

Student Class Participation grades are determined by Professor Love out of a maximum of 100 points. This determination is based on:

- 30 points for completing the [Welcome to 431  survey](https://bit.ly/431-2023-welcome-survey) that most of you did prior to class, and if you haven't done it, please do so now.
- plus up to 45 additional points for Minute Paper responses (5 points for each on-time submission, 3 points for late submissions within 24 hours of the deadline.)
- plus up to 35 bonus points for actions that help the class, as awarded during the semester

These bonus points have a small impact, generally, but include things like:

- finding typographical or coding errors in Professor Love's slides, notes and other published materials. Professor Love makes occasional typographic and grammatical errors, which irritate him enormously. Please post to Campuswire the details of any typos or errors you find in this syllabus or any other course materials. If you are the first to let us know, and we make the change, you will receive some credit in your class participation grade.
- asking especially helpful questions in the Minute Papers or on Campuswire
- providing helpful responses to questions and engaging in the discussion on Campuswire
- identifying interesting visualizations or uses of ideas we're discussing in class in the popular or scientific media (this is also done via Campuswire.)
- completing (in a timely fashion) special "partially hidden" tasks that Professor Love buries within longer documents to ascertain whether or not you're reading these documents effectively. For an example, see section 14 of this Syllabus.
- plus a few other things that come under the general heading of "being helpful."

Thanks to the bonus, scores up to 110 / 100 in Class Participation are technically possible. Bonus credit is capped so that no one's class participation score will exceed 105 points.

## Grading Labs

The seven Main Labs are graded by the Teaching Assistants, according to a rubric and answer sketch. In grading labs, everything counts, including the quality of the presentation, as well as the coding and statistical work. Grading for Lab X will be discussed as part of the Lab X instructions.

For each of the main 7 Labs, we publish a detailed answer sketch (by Noon the day after the deadline). Later, when the grades become available (roughly one week after the deadline) you will also receive the grading rubric used by the teaching assistants. You should expect to receive your grade on each Lab you submit on time roughly one week after the deadline. Along with the grade, on-time labs will receive modest feedback about the work. 

All Labs should be turned in by the deadline specified on the [Course Calendar](https://thomaselove.github.io/431-2023/calendar.html). In this class, it is far better to turn in timely, but only partially complete work than nothing at all. We don't give extensions on Labs. Instead, we use the following grading policy.

- To receive full credit on a Lab, it must be received on Canvas no later than 59 minutes after the posted deadline. (This allows for small issues with uploading to Canvas to occur without penalty.)
- Labs that are turned in 1-12 hours after the deadline will lose 10% of available points.
- Labs turned in more than 12 but less than 48 hours after the deadline will lose 30% of available points.
- No extensions to Lab deadlines will be permitted this semester. Labs turned in more than 48 hours after the deadline will receive no credit, since by then the Lab Sketch will be posted.

Your lowest lab score (out of the first seven) over the course of the semester will be dropped before we calculate your overall lab grade. 

- If you decide to skip a lab, please submit a note to Canvas by the deadline saying that you are skipping the lab.
- Should you run the risk of needing to miss more than one lab during the semester, contact Professor Love via email.

## Lab Appeal Policy - Request a Review via Google Form

Clarification of concerns related to potential typographical or other errors in our Lab answer sketches is welcome at any time, but haggling over points on assignments can be a real time sink in a large class. To that end, students are **requested not to dispute** any grading on Labs during the semester, but instead to request a review using the Google Form for Lab Appeals that can be found linked on the Assignments page on our main web site.

Should you receive a lower grade on a Lab than you feel you deserve based on the feedback the TA provides, the answer sketch and the grading rubric, you can submit a request for a regrade by Professor Love by submitting a request through a Google Form he will provide to you.

- On [the course's Labs page](https://github.com/THOMASELOVE/431-labs-2023), we include a section about Lab Regrade Requests. There, you'll find a link to the Lab Regrade Request Form (you must log into Google via CWRU to see it) listing all of the Labs. Any student who wishes to dispute points can specify the number of points in question for each item, and the details of the issues that concern them. 
    - All forms must be submitted by the deadline in December specified on the Course Calendar.
    - If you wish to dispute a grade, just fill out the form at any time before the deadline in December. You can edit the form after submitting it so that you can add additional requests up until the end of the semester.
    - Disputing a grade on a homework with a teaching assistant is pointless. 
    - Professor Love is responsible for all final grading decisions, and if you have a concern, you should submit your request through the form.
    
Students are welcome to ask questions of Professor Love about grading during the term. The TAs and Professor Love are happy to discuss in a general sense any questions about an assignment, but no grades will be changed until the end of the term. 
    - The one exception is if there is a mistake in adding up points, or some similar clerical error. If you find such an issue, please bring it to Professor Love's attention via email, and such problems will be corrected immediately.

In mid-December, **after** Professor Love has worked out what letter grade to give each student, he will go through the requests on the form and determine for each whether the student's letter grade would change if all of the points in dispute were granted. If the answer is no, then he won't even look at the disputed grade(s). If the answer is yes, then he will look very carefully to see if enough extra points are merited to change a grade. (It will not help your case to submit frivolous requests.)

The main advantage of this system is that it saves all of us the hassle of haggling over points that are never going to mean anything anyway. It also provides "equal access" to students who are too timid to express their concerns. Finally, if there is an issue with grading a particular problem or assignment that needs to be reconsidered, Professor Love will have access to all papers and can make a universal decision^[I got this idea from Jessica Utts.].

## Grading the Quizzes

Each quiz will be graded solely by Professor Love. A detailed answer sketch and grading rubric will be provided to you when grades are available, within 48 hours of the quiz deadline. 

In calculating your quiz average for your course grade, Professor Love weights your stronger Quiz performance at 60% and your other Quiz at 40%.

## Grading the Projects

Some elements of each project will be graded by Professor Love, and others by the teaching assistants.

In calculating your project average for your course grade, I will weight Project A at 40% and Project B at 60%.

Students who cannot complete a project (either A or B) in a timely fashion will receive an incomplete grade until both Projects are completed. A penalty will be applied to late work on projects. 

Once the complete project instructions are available, please contact Professor Love directly if you are in any way concerned about your ability to complete a project on time.

## Late Assignments

If an emergency arises that will keep you from timely completion of work that has a deadline, like a lab, minute paper, or the like, send an email directly to Professor Love saying the following:

I have an emergency that will keep me from completing (list things you’re worried about completing) in a timely fashion. I will contact you again when I am able to make plans.

Professor Love will respond with “OK” and temporarily excuse you from things until you send a “re-connection” email to make plans for making up the work you missed, at which time he’ll evaluate the situation and together you can make that plan. At no time do you owe us any information about your health or the nature of the emergency.


## Incomplete Grades

Here is the official University policy:

> The grade of Incomplete is assigned at the discretion of an instructor provided that:

> 1.	There are extenuating circumstances, explained to the instructor before the assignment of the grade, which clearly justify an extension of time beyond the requirements established for other students in the class. It is the student's responsibility to notify the instructor of the circumstances preventing completion.

> 2.	The student has been passing the course and only a small segment of the course remains to be completed, such as a term paper, for which the extenuating circumstances justify a special exception.

> An Incomplete grade may not be assigned if a student is absent from a final examination, unless the dean has authorized the absence. Unauthorized absence from a final examination will result in a failing grade. When the student completes the work, the Incomplete is changed to an A, B, C, D, P, F, or NP.

> All work for the incomplete grade must be made up and the change of grade recorded in the Office of the University Registrar by the date specified by the instructor, but no later than the last day of class in the semester following the one in which the Incomplete was received. A student who has a permanent Incomplete for a required course must retake the course in a later term. If the student cannot complete the work by the end of the following semester, he or she must petition for an extension which must be endorsed by the instructor, explain the reasons why the work has not been completed, and include a new date for completion. Students will be allowed only one extension of no more than one additional semester to complete the work for an Incomplete grade.
